server:
  port: 60001


person:
  last-name: 张三${random.uuid}
  age: ${random.int}
  birth: 1993/06/18
  boss: false
  list:
  - 1
  - 2
  map: {k1: v1,k2: v2}
  dog:
    name: ${person.hello:hello}_旺财
    age: 5

#指定激活yml文件
spring:
  profiles:
    active: dev
---
server:
  port: 60002
spring:
  profiles: dev
---
server:
  port: 60003
spring:
  profiles: prod


## 激活指定的配置文件或者文档块
#spring:
#  profiles:
#    active: dev
#命令行模式也能激活指定的profile
#java -jar (jar包名称) --spring.profiles.active=prod

# 配置文件加载位置
